### PR TITLE
Smelting ore in order to create shielding

### PR DESCRIPTION
**Pull request by basilicofresco**
Smelting ore in order to produce shielding seems more reasonable for a base than using pressed poo. :)
I kept the same conversion rate of the Waste Compressor. Let me know what you think.

### CODE REVIEW

**Comment by lordcirth** [comment]
"Ore Smelter" sounds awfully vague.  Also what metal is this shielding?  Kerbalism processes usually include comments specifying what chemical reaction the process is balanced based on.

**Comment by basilicofresco** [comment]
It was just a starting point. :)
Heavy metals extraction? 
Iron extraction?
Lead is not common, but iron concentration is actually pretty good in Mars/Moon/asteroids soils.

**Comment by basilicofresco** [comment]
@lordcirth Apparently iron is actually used in lead-free radiation shielding applications, is just less effective then lead. For example with gamma rays it requires more or less twice the thickness of a lead shielding.
http://www.eichrom.com/PDF/gamma-ray-attenuation-white-paper-by-d.m.-rev-4.pdf

Do you like "Iron Extractor --> _Process Ore to extract metal, for use in radiation shielding_"?
Does "Iron Smelter" sound better?

**Comment by lordcirth** [comment]
Cool, good to know.  So, I just looked it up in the source:
 https://github.com/ShotgunNinja/Kerbalism/blob/master/GameData/Kerbalism/Profiles/Default.cfg#L348  
And apparently Kerbalism assumes that Ore is Ilmenite, which contains iron and titanium!  So all you need to do is calculate the masses to balance your input/output.  Although, iron being heavier than lead per shielding might be a problem...

https://en.wikipedia.org/wiki/Ilmenite

**Comment by basilicofresco** [comment]
@lordcirth  I was not aware that [real molten regolith electrolysis actually produces metal at the cathode](http://isru.nasa.gov/Molten_Regolith_Electrolysis.html). It is very interesting... I guess that we can discard the smelter idea and just insert shielding as byproduct of MRE.

I will do the math and I will write something on the forum because we should rethink a bit the MRE.

**Pull request closed without merging**
