### PR TITLE
Support for custom antenna scopes

### PR DESCRIPTION
**Pull request by dbent**
@ShotgunNinja This PR allows mods and users to declare custom, fixed-range, scopes for antennae.

I really appreciate the fact that Kerbalism will automatically adapt to any given system and that works very well, but in my case I want to play a 6.4x rescale with OPM with Ven's Stock Revamp antennae. Between Ven and Stock there are 8 antennae that I want to give very specific ranges to.

Basically this allows you can declare a MM patch like so:
```
KERBALISM
{
    ANTENNA
    {
        SCOPE
        {
            name = kilo
            value = 1e3
        }
        
        SCOPE
        {
            name = mega
            value = 1e6
        }
        
        SCOPE
        {
            name = giga
            value = 1e9
        }
        
        SCOPE
        {
            name = tera
            value = 1e12
        }
        
        SCOPE
        {
            name = peta
            value = 1e15
        }
    }    
}

@PART[shortAntenna]:NEEDS[Kerbalism]:AFTER[Kerbalism]
{
    @MODULE[Antenna]
    {
        %scope = kilo
    }
}

@PART[longAntenna]:NEEDS[Kerbalism]:AFTER[Kerbalism]
{
    @MODULE[Antenna]
    {
        %scope = mega
    }
}

@PART[mediumDishAntenna]:NEEDS[Kerbalism]:AFTER[Kerbalism]
{
    @MODULE[Antenna]
    {
        %scope = giga
    }
}

@PART[commDish]:NEEDS[Kerbalism]:AFTER[Kerbalism]
{
    @MODULE[Antenna]
    {
        %scope = tera
    }
}

@PART[HighGainAntenna]:NEEDS[Kerbalism]:AFTER[Kerbalism]
{
    @MODULE[Antenna]
    {
        %scope = peta
    }
}

```

I've chosen to use `GameDatabase` rather than parsing the Settings file directly so that other mods could potentially add scopes. (You may consider using `GameDatabase` for general settings parsing so that mods can alter settings, or users can write MM patches against it without having to edit `Settings.cfg` and potentially forgetting to merge their changes with every update).

The one "downside" to this is that the ranges have to be fixed expressions and can't dynamically scale with the system.

As a bonus, I've modified the `Range()` method so that if the scope isn't found in `range_values` it returns `0` rather than throwing an exception.

On a related note I noticed that the code in the repository as it exists now contains the following in `Lib.cs`:
```c#
static System.Random rng = new System.Random((int)DateTime.Now.Ticks);
```

That throws an immediate OverflowException since `DateTime.Now.Ticks` is well over the maximum value for `Int32`. It's unnecessary too since just calling `Random()` uses a seed based on the current time anyway. I assume the released builds of Kerbalism don't contain this code, otherwise nothing would work. But I can easily see this frustrating potentially contributors; I know it took me a bit to figure out what the problem trying to get Kerbalism to run with my builds.

### CODE REVIEW

**Comment by ShotgunNinja** [comment]
This is good. I'm going to merge manually, as you may have figured out I'm using github only as an archive...

I'm already using GameDatabase for the settings, it is somehow buried in the Lib.ParseConfig function.

For the random seed... I'll use the default constructor (and you are absolutely right) The strange thing is that there is the same code in production but it is not throwing an overflow exception.

Finally I want to take the chance to thank you for splitting the CKAN package in two, that was very appreciated and will open the road to third party profiles, not to mention those that only want a backround simulation of resources without the rest.

**Comment by dbent** [comment]
> I'm already using GameDatabase for the settings, it is somehow buried in the Lib.ParseConfig function.

Ah, didn't notice, I guess if I want to write a MM patch against it I would have to target the `Settings` node, i.e.

```
@Settings
{
    %MessageLength = 1000
}
```
At least until MM has some way of targeting a specific path/file. You may want to consider "namespacing" the `Settings` node under a `Kerbalism` or `KERBALISM` node (I went with `KERBALISM` in the PR to basically keep with Squad's convention for node names).

> For the random seed... I'll use the default constructor (and you are absolutely right) The strange thing is that there is the same code in production but it is not throwing an overflow exception.

I suppose the releases are built in Release mode, not Debug mode? OverflowException probably isn't thrown in Release mode.

> Finally I want to take the chance to thank you for splitting the CKAN package in two, that was very appreciated and will open the road to third party profiles, not to mention those that only want a backround simulation of resources without the rest.

No problem, and when KSP-CKAN/CKAN#1728 is merged we should be able to support the other profiles that are shipped in the archive.

**Comment by ShotgunNinja** [comment]
Good point on Settings, I'll rename it to 'Kerbalism'.

I merged this (in my local version), with some small changes and an addition.

The scopes are definited like this, in the global namespace:
```
AntennaScope
{
  name = my_custom_scope
  range = 1e13
}
```

And it is also possible to redefine the default scopes, like this:
```
AntennaScope
{
  name = orbit
  range = 1e6
}
```

About CKAN packages for the other profiles... man that is just great! Thanks a lot.

**Comment by ShotgunNinja** [comment]
This is in the new release now. Thanks again.

**Pull request closed without merging**
