### PR TITLE
Process resources tweaks etc

### PR DESCRIPTION
**Pull request by PiezPiedPy**
Made changes to some of the processes resource ammounts, made the EVA scrubber more efficient, added a waste incinerator chemical process to ISRU's, added shield resource to stock nuclear parts and some antenna tweeks.

### CODE REVIEW

**Comment by ShotgunNinja** [comment]
I'm trying to understand the changes in processes. I'm not saying they are wrong. On the contrary, I admit to be a complete chemistry noob, so maybe you can help me understand.

For example, I'm rechecking all the reactions on my spreadsheet and lets take the water electrolysis.
Now, going [here](http://www.webqc.org/balance.php) to balance lead to:
  
`2x H2O -> 2x H2 + O2`

 . | coeff | molar mass
--|--|--
H2O	| 2x	| 18.01528	
H2	| 2x	| 2.01588	
O2	| 1	| 31.9988

With these proportions, and using CRP densities for the elements, there is violation of mass conservation: input mass is 8.42% greater than output mass. I want to understand why.

Am I right in assuming that the error is in fact in the difference between CRP densities and whatever the software at the site linked is using? If not, where am I borking instead?

**Comment by PiezPiedPy** [comment]
Regarding how you have an 8.42% input mass greater than the output is a mystery to me, I'm no chemistry professor either but as far as I know the error should not be due to the densities, though I could be wrong. I've attached a copy of my Spreadsheet for you to look at, maybe it can help you find your problem.

I was previously using real densities in the spreadsheet and have now changed over to the CRP densities.
 This spreadsheet is using the CRP values -> [KSP Kerbalism process calc.xlsx](https://github.com/ShotgunNinja/Kerbalism/files/863247/KSP.Kerbalism.process.calc.xlsx)

 In my calculations for each element in a process. I've used Avogadro's constant and Molar Mass to determine Total Mass.
 I've then used a volume of 5 Litres along with density to calculate the mass of one KSP Unit of each element.
 Next is to calculate how many iterations of the reaction can be produced using the entire mass of a single KSP Unit of an input resource.
 Then I can derive the number of KSP Units for each element needed to satisfy the process.

**Comment by YaarPodshipnik** [comment]
Why the changes to antennas?

**Comment by PiezPiedPy** [comment]
@YaarPodshipnik Re:
> Why the changes to antennas?

The power usage of the antennas is very high, i.e. a mobile phone will use approx. 500mW (Half a Watt or 0.0005 EC) and have a +40km range.
 Take Voyager-1 for example, it is nearly 20 billion km away and has a transmitter power of 20W (0.02 EC) and can still be received because of the very high gain of the radio telescope array that is used to receive the signal from Voyager.

The problem I have with the antennas in Kerbalism at the moment is the use of the term low-gain and high-gain and its association with the relay function.
 The gain of an antenna is how good it is at receiving a signal, the higher the gain the lower/weaker the signal it can hear, it has nothing to do with the transmission power and relay is purely a function of the radio equipment's capability to transmit a received signal back out.
 Depending on the type of radio equipment, you can receive (Rx) just like an average music radio _receiver_ (uses gain), you can transmit (Tx) like a radio station _transmitter_ does (uses power), or you can do both (Tx/Rx) like a HAM radio _transceiver_ or a mobile phone, but you cant Rx and Tx at the same time with the same antenna.
Or you could look at it as a High-gain antenna is like having big ears but does not mean you have a mouth, you need power for a mouth. Or you could say a High powered antenna is a big mouth that even low-gain little ears can pickup, some can also be big mouthed and have big ears just like my ex :|

**Comment by ShotgunNinja** [comment]
The terms low-gain / high-gain are used in this mod to indicate **'ominidirectional' / 'directional'**.

I didn't come up with these terms usage either, rather it is used in general.

The origin of the usage of these terms to indicate directionality could be related to the fact that, at parity of overall capability over the sphere, the most directional antenna will have the strongest signal.

In this mod, when you switch 'relay' on in an antenna, you are enabling data reception from other vessels. Why is this only included in the 'low-gain' (omnidirectional) antennas? Because in this mod the 'high-gain' (directional) antennas are always pointed to the DSN on Kerbin/Earth ground. Therefore, it would be pointless for them to have a flag that enable data reception from other vessels.

**Comment by ShotgunNinja** [comment]
To further clarify about the term gain (I had to re-check, I'm not an expert on these matters by any mean), this is what wikipedia says about the matter:

> In electromagnetics, an antenna's power gain or simply gain is a key performance number which combines the antenna's directivity and electrical efficiency

> A high-gain antenna (HGA) is a directional antenna with a focused, narrow radiowave beam width. 

> By contrast, a low-gain antenna (LGA) is an omnidirectional antenna with a broad radiowave beam width.

**Comment by PiezPiedPy** [comment]
I was assuming the directionless independent gain, I was totally unaware that the specific terms high-gain and low-gain are used in general to refer to directional and omnidirectional antennas. (Who the hell came up with that !?)
 Anyway, I can now see why the antenna function the way they do with the relay's only on the omnidirectional (low-gain) antennas. ;)

**Comment by ShotgunNinja** [comment]
I was checking the waste incinerator, and got totally different values:

**Waste Incinerator**  | Resource | Weight (Kg) | Density(Kg/unit) | Units
--|-----------|--------------|--------------------|----------
H18C82 |	Waste |	0.00008120 |	0.00075 |	0.108266667
O2 |	Oxygen |	0.00022408 |	0.00141 |	0.158919425
CO2 | -> CarbonDioxide |	0.00029215 |	0.00195 |	0.149743960
H2O	| - >Water |	0.00001313 |	1.00000 |	0.000013126

The weights of the reaction components were obtained from this online calculator [here](http://www.webqc.org/balance.php?reaction=H18C82%2BO2%3DCO2%2BH2O), then normalized against waste production per-second per-crew.

The reaction conserve mass, that is the inputs and outputs weights are equivalent.

Your values, instead, lead to a **-36%** variation in mass after the reaction.

**Comment by ShotgunNinja** [comment]
The previous comment was edited (sorry about that), there was a mistake on the spreadsheet used to check the waste incinerator values of @PiezPiedPy.

Discussion on useful bits of this commit has moved:
- Waste Incinerator: #90
- EVA scrubber: #91

**Comment by PiezPiedPy** [comment]
No worries and I'll keep any commits smaller next time. Thanks for looking.

**Pull request closed without merging**
