### PR TITLE
Added basic integration with RemoteTech.

### PR DESCRIPTION
**Pull request by neochief**
Here's a basic attempt to allow Kerbalism work together with RemoteTech.

If user installs both mods, the antenna parts of the Kerbalism will be disabled and all connectivity stuff will be handled by RemoteTech.

It is possible to go further and calculate energy consumption and entertainment using RemoteTech part modules, but I'm not sure whether it worth doing since the resulting code will look kinda ugly. We could always add it later if needed.

Here's the compiled dll for testing: https://dl.dropboxusercontent.com/u/406311534/web/Kerbalism.dll (You will need to paste it to the GameData/Kerbalism and the replace default one)

### CODE REVIEW

**Comment by ShotgunNinja** [comment]
This is good and i see you deal with pretty much everything. I'm going to merge it manually. Will keep this open until then.

**Comment by neochief** [comment]
Great, thanks!

**Comment by ShotgunNinja** [comment]
Done, in next version 0.9.9.5. Also disable the signal mechanic if there is AntennaRange

**Comment by RickKerman** [comment]
Thank you for this, now Kerbalism is the best reality/fun mod out there.

**Pull request closed without merging**
