### PR TITLE
Add Regolith Pyrohydrolisis to extract Lithium

### PR DESCRIPTION
**Pull request by YaarPodshipnik**
* add Regolith Pyrohydrolisis process to default profile
* add RPH setup to ISRUs if Near Future Propulsion is installed
* add definition of Lithium to resources (same as in CRP)
* ~~fix missing tags on small Chemical Plant~~ - tags are special in Kerbalism, I won't touch them

All process efficiency values are rather arbitrary, please adjust as you see fit.

### CODE REVIEW

**Comment by ShotgunNinja** [comment]
The profile is parsed before MM apply the patches, because it is used to determine features to enable, that are then injected as MM patches themselves. That is why any MM patch targeting a profile will be ignored. Not only that, but in the profile itself no MM directives can be used.

It is a limitation that is not desiderable, but I don't know if that can be improved in future without rethinking the whole MM patch injection system. 

Meanwhile your solution of adding the process directly to the profile is okay, as the user that don't have NF installed will have no ProcessController using it anyway. So that will do for now.

The parts all have no tags field defined because I am abusing for various reasons:
- all parts with _tags_ field containing __kerbalism_ will appear under the heartbeat custom category in VAB
- all parts have _category_ field set to _none_
- no parts have _tags_ defined (so they are de-facto hidden and disabled)
- in _Misc.cfg_, I enable the parts (if they are somewhat used) by setting their _tags_ to __kerbalism_
- in any case, searching by tags will not work because _category_ is _none_ (it is a stock KSP limitation)

For example the chemical plant is enabled if it has at least a module (after MM patches are applied).

To balance the process inputs and outputs I used these very useful calculators:
[BalanceReactions](http://theodoregray.com/PeriodicTable/MSP/BalanceReactions) and [Thermodynamics Calculator](http://www.shodor.org/unchem/advanced/thermo/thermocalc.html). I'm a chemistry noob myself and these sites helped a lot. The reaction has to be physically possible in reality however, or the calculators will not work.

**Comment by ShotgunNinja** [comment]
I forgot: _Lithium_ resources should also be defined in _Resources.cfg_. The reason is that CRP is not an hard-requirement anymore.

**Comment by YaarPodshipnik** [comment]
Thanks for the explanations and the links. I'll make the changes based on your comments. I think that for now keeping the inputs at the same level as NFT itself does is the right thing to do. I will try to dig out and understand how the process should actually work and submit an adjustment at a future date.

**Comment by ShotgunNinja** [comment]
This is made obsolete by [this change](https://github.com/ShotgunNinja/Kerbalism/commit/90c8aa11326927f6ebd43a457ac9fd22e2d5d39c).

In default profile, only the stock conversions (Lf+Ox,LiquidFuel,Oxidizer,Monoprop) are now removed from the ISRU parts. So the conversions added by third-party mods are not touched.

**Pull request closed without merging**
