### PR TITLE
Add support for Sounding Rockets and Bluedog Design Bureau.

### PR DESCRIPTION
**Pull request by ValynEritai**
Simple configuration, data transfer isn't needed due to packages needing
lab analysis and the range is the same as in the standard mod.

Should be right for merging as is,

### CODE REVIEW

**Comment by ValynEritai** [comment]
I just added support for Bluedog Design Bureau as well.

**Comment by ShotgunNinja** [comment]
Thanks a lot. I'll merge this before 1.1.9 release (in a week or two).

**Comment by ValynEritai** [comment]
Sweet. Thanks!

**Comment by ShotgunNinja** [comment]
I have some critiques/comments:

- Antenna _dist_ are better expressed in scientific notation, due to the vast differences in magnitude of the values.
- Antenna _dist_ values need to be choosen carefully, together with the _rate_ of transmission. The resulting transmission rates at various distances can be seen in the part tooltip in the VAB: that could help you balance them. It may be also useful to compare the resulting rates with the ones from the stock antennas (as defined in Signal.cfg), instead of CommNet 'power'.
- Personally I don't like internal antennas in pods, because there are 9 different antenna parts available in stock now. I think adding these was a very bad design decision from SQUAD. That is why I don't add internal antennas to stock pods. That being said, it is up to you to decide if these pods should have internal antennas or not.

**Comment by ValynEritai** [comment]
Alright. I'll work on this some more then. Hopefully I can get this right.

**Comment by ValynEritai** [comment]
Should be a lot more balanced now. See my comments in 85dc5ec.

**Comment by ValynEritai** [comment]
I've reverted that last balance fix as it's coming up way too short for my liking.

**Comment by Maxzhao1999** [comment]
I've realised that you have not modifiled the Bluedog science module yet so I've made it myself, hope it is okay
```
@PART[bluedog_MOL_Lab]:NEEDS[FeatureScience]:FOR[Kerbalism]:AFTER[Bluedog_DB]
{
  !MODULE[ModuleScienceLab] {}
  !MODULE[ModuleScienceConverter] {}

  MODULE
  {
    name = Laboratory
    researcher = Scientist
    analysis_rate = 0.003 // 3 kbps (since it's a smaller and earlier along the tech tree)
    ec_rate = 0.9
  }
}

**Comment by ValynEritai** [comment]
Oh! Whoops!

Feel free to fork my fork and add that, I'll pull it straight in. haha

**Pull request merged**
